# zsh-syntax-highlighting — Catppuccin Rose / Outrun accents

ZSH_HIGHLIGHT_STYLES[comment]='fg=8'
ZSH_HIGHLIGHT_STYLES[alias]='fg=13'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=13'
ZSH_HIGHLIGHT_STYLES[function]='fg=12'
ZSH_HIGHLIGHT_STYLES[command]='fg=12'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=5'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=13'
ZSH_HIGHLIGHT_STYLES[string]='fg=5'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=5'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=5'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=5'
ZSH_HIGHLIGHT_STYLES[variable]='fg=13'
ZSH_HIGHLIGHT_STYLES[path]='fg=14'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=5'
ZSH_HIGHLIGHT_STYLES[option-flag]='fg=12'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=9,bold'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=14'
ZSH_HIGHLIGHT_STYLES[assign]='fg=13'
ZSH_HIGHLIGHT_STYLES[default]='fg=7'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=12'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=14,bold'
