os:
  editPreset: "nvim-remote"

customCommands:
  - key: "C"
    command: "ai-commit"
    context: "files"
    description: "Commit with AI-generated message"
    output: popup
gui:
  nerdFontsVersion: "3"
  authorColors:
    "*": "#babbf1"
  branchColorPatterns:
    "^main$": "#a6d189"
    "^master$": "#a6d189"
    "^feat(ure)?/": "#8caaee"
    "^fix/": "#e78284"
    "^hotfix/": "#e78284"
  theme:
    # Catppuccin Frappe theme
    activeBorderColor:
      - "#babbf1"
      - bold
    inactiveBorderColor:
      - "#737994"
    searchingActiveBorderColor:
      - "#8caaee"
      - bold
    optionsTextColor:
      - "#a5adce"
    selectedLineBgColor:
      - "#51576d"
    inactiveViewSelectedLineBgColor:
      - "#414559"
    cherryPickedCommitFgColor:
      - "#99d1db"
    cherryPickedCommitBgColor:
      - "#344a40"
    markedBaseCommitFgColor:
      - "#303446"
    markedBaseCommitBgColor:
      - "#e5c890"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
git:
  diffRenderers:
    - colorArg: always
      command: 'delta --dark --paging=never --syntax-theme "Catppuccin Frappe" --plus-style "syntax #264542" --plus-emph-style "syntax #264542" --minus-style "syntax #3b2234" --minus-emph-style "syntax #3b2234"'
