return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "frappe",
      transparent_background = true,
      background = {
        light = "latte",
        dark = "frappe",
      },
      color_overrides = {
        frappe = {
          -- Rose Pine Moon UI
          base = "#232137",
          mantle = "#1f1d30",
          crust = "#1f1d30",
          surface0 = "#2a273f",
          surface1 = "#393552",
          surface2 = "#44415a",
          overlay0 = "#56526e",
          overlay1 = "#6e6a86",
          overlay2 = "#908caa",
          text = "#d8d3ea",
          subtext0 = "#908caa",
          subtext1 = "#c4a7e7",

          -- Keep the Catppuccin feel, but shift the accents to your blend
          green = "#a6d189",
          teal = "#c4a7e7",
          sky = "#babbf1",
          sapphire = "#8caaee",
          blue = "#8caaee",
          lavender = "#c4a7e7",
          mauve = "#c6a0f6",
        },
      },
      custom_highlights = function(colors)
        return {
          Normal = { bg = "#232137", fg = colors.text },
          NormalNC = { bg = "#232137", fg = colors.text },
          EndOfBuffer = { bg = "#232137", fg = "#232137" },
          -- Nudge the UI closer to Rose Pine Moon in places Catppuccin styles differently
          CursorLine = { bg = "#393552" },
          ColorColumn = { bg = "#393552" },
          CursorLineNr = { fg = colors.text, bold = true },
          LineNr = { fg = "#6e6a86" },
          SignColumn = { bg = "#232137" },
          FoldColumn = { bg = "#232137", fg = "#6e6a86" },
          NormalFloat = { bg = "NONE", fg = colors.text },
          FloatBorder = { bg = "NONE", fg = "#393552" },
          FloatTitle = { bg = "NONE", fg = colors.iris or colors.lavender },
          Pmenu = { bg = "NONE", fg = colors.text },
          PmenuSel = { bg = "#393552", fg = colors.text },
          PmenuSbar = { bg = "NONE" },
          PmenuThumb = { bg = "#56526e" },
          StatusLine = { bg = "NONE", fg = colors.text },
          StatusLineNC = { bg = "NONE", fg = "#6e6a86" },
          WinSeparator = { fg = "#393552" },
          VertSplit = { fg = "#393552" },
          Visual = { bg = "#393552" },
          Search = { bg = "#393552", fg = colors.gold or colors.yellow },
          IncSearch = { bg = colors.green, fg = colors.base },
          SnacksPicker = { bg = "NONE", fg = colors.text },
          SnacksPickerBorder = { bg = "NONE", fg = "#393552" },
          SnacksPickerInput = { bg = "NONE", fg = colors.text },
          SnacksPickerInputBorder = { bg = "NONE", fg = "#393552" },
          SnacksPickerList = { bg = "NONE", fg = colors.text },

          -- Make a few language/LSP choices feel more Frappe than Moon
          ["@variable"] = { fg = colors.text },
          ["@variable.member"] = { fg = colors.lavender },
          ["@variable.parameter"] = { fg = colors.maroon },
          ["@property"] = { fg = colors.lavender },
          ["@type.builtin"] = { fg = colors.mauve },
          ["@keyword.import"] = { fg = colors.mauve },
          ["@constructor"] = { fg = colors.yellow },
          ["@constant.java"] = { fg = colors.lavender },
          String = { fg = "#81c8be" },
          ["@string"] = { fg = "#81c8be" },
          ["@string.escape"] = { fg = "#81c8be" },
          ["@string.regex"] = { fg = "#81c8be" },

          DiagnosticInfo = { fg = colors.sky },
          DiagnosticHint = { fg = colors.teal },
          DiagnosticOk = { fg = colors.green },
          GitSignsAdd = { fg = colors.green },
          DiffAdd = { fg = colors.green },
        }
      end,
      integrations = {
        blink_cmp = true,
        gitsigns = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "underline" },
            hints = { "underline" },
            warnings = { "underline" },
            information = { "underline" },
            ok = { "underline" },
          },
        },
        noice = true,
        notify = true,
        snacks = true,
        telescope = true,
        treesitter = true,
      },
    },
  },
}
