org.eclipse.jdt.core.formatter.lineSplit=120
org.eclipse.jdt.core.formatter.continuation_indentation=1
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_allocation_expression=20
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_explicit_constructor_call=20
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_method_invocation=20
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_constructor_declaration=20
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration=20
